# Generated by Django 5.1.4 on 2024-12-21 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='size_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
                ('category_image', models.TextField(max_length=100)),
                ('category_description', models.CharField(max_length=100)),
                ('size_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.size_category')),
            ],
        ),
        migrations.CreateModel(
            name='size_option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=100)),
                ('sort_order', models.CharField(max_length=100)),
                ('size_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.size_category')),
            ],
        ),
    ]
