# Generated by Django 5.1.4 on 2024-12-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_brand_colour_product_product_item_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_category',
            name='category_description',
            field=models.TextField(max_length=1000),
        ),
    ]
