# Generated by Django 5.1.4 on 2024-12-22 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_product_about_alter_product_care_instructions_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_item',
            old_name='colour_id',
            new_name='colour_name',
        ),
    ]
