# Generated by Django 5.1.4 on 2024-12-22 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_colour_id_product_item_colour_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_item',
            old_name='colour_name',
            new_name='colour_id',
        ),
    ]
