# Generated by Django 5.1.4 on 2024-12-22 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_colour_name_product_item_colour_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_image',
            old_name='product_item_id',
            new_name='product_item_d',
        ),
    ]
