# Generated by Django 5.1.4 on 2024-12-22 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_product_item_id_product_image_product_item_d'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_image',
            old_name='product_item_d',
            new_name='product_item_id',
        ),
    ]
