# Generated by Django 5.1.4 on 2024-12-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_rename_product_item_d_product_image_product_item_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
        migrations.AddField(
            model_name='product_item',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
        migrations.AddField(
            model_name='product_item',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
        migrations.AddField(
            model_name='product_item',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='product_image/'),
        ),
        migrations.AddField(
            model_name='product_item',
            name='product_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product_item',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
