# Generated by Django 5.1.4 on 2024-12-24 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_product_item_image1_product_item_image2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('phone', models.IntegerField(max_length=15, null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
