# Generated by Django 5.1.4 on 2024-12-24 10:07

import django.db.models.deletion
import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_usermodel_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(blank=True, max_length=100, null=True)),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('pincode', models.CharField(max_length=100)),
                ('default', models.BooleanField(default=False)),
                ('user_adrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=1)),
                ('product_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product_item')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.size_option')),
                ('user_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user_pymt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel')),
            ],
        ),
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_code', models.CharField(blank=True, max_length=100, null=True)),
                ('startdate', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('being_delivered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.orderitemmodel')),
                ('shipping_adrs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addressmodel')),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodel')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.paymentmodel')),
            ],
        ),
    ]
