# Generated by Django 5.1.4 on 2024-12-24 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_addressmodel_orderitemmodel_paymentmodel_ordermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addressmodel',
            old_name='user_adrs',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='orderitemmodel',
            old_name='user_item',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='ordermodel',
            old_name='user_order',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='paymentmodel',
            old_name='user_pymt',
            new_name='user',
        ),
    ]
