# Generated by Django 5.1.4 on 2024-12-25 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_addressmodel_address_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='address_type',
            field=models.CharField(blank=True, choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1),
        ),
    ]
