# Generated by Django 5.1.4 on 2024-12-26 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_addressmodel_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='password2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
