# Generated by Django 5.1.4 on 2024-12-27 04:49

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_usermodel_password2'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserModels',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to=settings.AUTH_USER_MODEL)),
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('Fullname', models.CharField(max_length=100)),
                ('phone', models.IntegerField(null=True)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='profile_picture/')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodels'),
        ),
        migrations.AlterField(
            model_name='orderitemmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodels'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodels'),
        ),
        migrations.AlterField(
            model_name='paymentmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodels'),
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
