# Generated by Django 5.1.4 on 2024-12-27 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_usermodels_alter_addressmodel_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addressmodel',
            name='user',
        ),
        migrations.AlterField(
            model_name='usermodels',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.addressmodel'),
        ),
    ]
