# Generated by Django 5.1.4 on 2024-12-27 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_addressmodel_user_alter_usermodels_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addressmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.usermodels'),
        ),
    ]
