# Generated by Django 5.1.4 on 2024-12-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_addressmodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmodel',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=2),
        ),
    ]
