# Generated by Django 5.1.4 on 2024-12-27 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_paymentmodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='bill_adrs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Billing', to='app.addressmodel'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='being_delivered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='ordered',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='ordered_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='received',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='refund_granted',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='refund_requested',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='shipping_adrs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shipping', to='app.addressmodel'),
        ),
    ]
