# Generated by Django 5.1.4 on 2024-12-27 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_ordermodel_bill_adrs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodels',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female')], max_length=10, null=True),
        ),
    ]
