# Generated by Django 5.1.4 on 2024-12-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_usermodels_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodels',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], max_length=10, null=True),
        ),
    ]
