# Generated by Django 5.1.4 on 2025-01-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_category',
            name='size_category_id',
        ),
        migrations.AddField(
            model_name='product_category',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
