# Generated by Django 5.1.4 on 2025-01-03 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_product_category_parent_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_category_id',
            new_name='product_category',
        ),
    ]
