# Generated by Django 5.1.4 on 2025-01-03 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_rename_product_category_id_product_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_item',
            old_name='product_id',
            new_name='product',
        ),
    ]
