# Generated by Django 5.1.4 on 2025-01-03 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_product_id_product_item_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_item',
            old_name='colour_id',
            new_name='colour',
        ),
    ]
