# Generated by Django 5.1.4 on 2025-01-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_alter_product_category_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='size_option',
            name='slug',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
