# Generated by Django 5.1.4 on 2025-01-06 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_size_option_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_item',
            name='sizeoption',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.size_option'),
        ),
    ]
