# Generated by Django 5.1.4 on 2025-01-06 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_product_item_sizeoption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemmodel',
            name='size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.size_option'),
        ),
    ]
